name       : vulkan-headers
version    : 1.1.101
release    : 3
source     :
    - https://github.com/KhronosGroup/Vulkan-Headers/archive/v1.1.101.tar.gz : 9b6180cd414071e22b2c4260b7e22c11fe830fced1c859b09610aa8a142b2c1d
license    : Apache-2.0
component  : programming
summary    : Vulkan Header files and API registry
description: |
    Vulkan Header files and API registry
patterns   :
    - /usr/include
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
