name       : vulkan-headers
version    : 1.2.141.0
release    : 8
source     :
    - https://github.com/KhronosGroup/Vulkan-Headers/archive/sdk-1.2.141.0.tar.gz : 579d112433c89ac8a4a93741bfa6eee8dca4a1d8145363a28d6d9967babc2b07
license    : Apache-2.0
component  : programming
summary    : Vulkan Header files and API registry
description: |
    Vulkan Header files and API registry
patterns   :
    - /usr/include
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
