name       : vulkan-headers
version    : 1.2.170.0
release    : 11
source     :
    - https://github.com/KhronosGroup/Vulkan-Headers/archive/sdk-1.2.170.0.tar.gz : d8e6050230ca678bcb0e7dc68d5984290da6eb655e8da9d08b5eaab1e84a7da9
license    : Apache-2.0
component  : programming
summary    : Vulkan Header files and API registry
description: |
    Vulkan Header files and API registry
patterns   :
    - /usr/include
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
