name       : vulkan-headers
version    : 1.2.154.0
release    : 9
source     :
    - https://github.com/KhronosGroup/Vulkan-Headers/archive/sdk-1.2.154.0.tar.gz : a0528ade4dd3bd826b960ba4ccabc62e92ecedc3c70331b291e0a7671b3520f9
license    : Apache-2.0
component  : programming
summary    : Vulkan Header files and API registry
description: |
    Vulkan Header files and API registry
patterns   :
    - /usr/include
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
