name       : vulkan-headers
version    : 1.2.198.0
release    : 15
source     :
    - https://github.com/KhronosGroup/Vulkan-Headers/archive/refs/tags/sdk-1.2.198.0.tar.gz : 34782c61cad9b3ccf2fa0a31ec397d4fce99490500b4f3771cb1a48713fece80
license    : Apache-2.0
component  : programming
summary    : Vulkan Header files and API registry
description: |
    Vulkan Header files and API registry
patterns   :
    - /usr/include
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
