name       : vulkan-headers
version    : 1.1.106.0
release    : 4
source     :
    - https://github.com/KhronosGroup/Vulkan-Headers/archive/sdk-1.1.106.0.tar.gz : 61eba1be3c4eed6bef9745ec8d8767869eacb6daff6d5b98951052910b73de8f
license    : Apache-2.0
component  : programming
summary    : Vulkan Header files and API registry
description: |
    Vulkan Header files and API registry
patterns   :
    - /usr/include
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
