name       : vulkan-headers
version    : 1.1.82.0
release    : 1
source     :
    - https://github.com/KhronosGroup/Vulkan-Headers/archive/sdk-1.1.82.0.tar.gz : df73da07d547cfbe88a797802401ea8225e4844e13d4fde52a7cb6e00e5179e5
license    : Apache-2.0
component  : programming
summary    : Vulkan Header files and API registry
description: |
    Vulkan Header files and API registry
patterns   :
    - /usr/include
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
