name       : vulkan-headers
version    : 1.2.182.0
release    : 13
source     :
    - https://github.com/KhronosGroup/Vulkan-Headers/archive/refs/tags/sdk-1.2.182.0.tar.gz : 61c05dc8a24d5a9104ca2cd233cb9febc3455d69a64e404c3535293f3a463d02
license    : Apache-2.0
component  : programming
summary    : Vulkan Header files and API registry
description: |
    Vulkan Header files and API registry
patterns   :
    - /usr/include
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
