name       : vulkan-headers
version    : 1.2.176.0
release    : 12
source     :
    - https://github.com/KhronosGroup/Vulkan-Headers/archive/refs/tags/sdk-1.2.176.0.tar.gz : 211d8552c5cf8b0607323d69c251d9c4639f89550f8de3d51d3995b5cdd737fb
license    : Apache-2.0
component  : programming
summary    : Vulkan Header files and API registry
description: |
    Vulkan Header files and API registry
patterns   :
    - /usr/include
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
