name       : vulkan-headers
version    : 1.3.231.0
release    : 17
source     :
    - git|https://github.com/KhronosGroup/Vulkan-Headers.git : sdk-1.3.231.0
license    : Apache-2.0
component  : programming
summary    : Vulkan Header files and API registry
description: |
    Vulkan Header files and API registry
patterns   :
    - /usr/include
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
