name       : vulkan-headers
version    : 1.2.131.1
release    : 6
source     :
    - https://github.com/KhronosGroup/Vulkan-Headers/archive/sdk-1.2.131.1.tar.gz : bd6873060c6988b62b938d7cb7e3152f006f44fbfaa9ce4b7f555b20ec77c53d
license    : Apache-2.0
component  : programming
summary    : Vulkan Header files and API registry
description: |
    Vulkan Header files and API registry
patterns   :
    - /usr/include
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
